---
# tasks file for ust_server
# include general variables
# - include_vars: vars/admin_users.yml

# Site specific
- include_vars: vars/sites/site_{{ sitecode }}.yml

# UST specific files/directories
- import_tasks: subtasks/files.yml
- import_tasks: subtasks/packages.yml
- import_tasks: subtasks/authentication.yml
- import_tasks: subtasks/admin_accts.yml
