---
# tasks file for ust_server
# UST specific files/directories
- import_tasks: subtasks/files.yml
- import_tasks: subtasks/packages.yml
- import_tasks: subtasks/admin_accts.yml
- import_tasks: subtasks/authentication.yml
