#!/bin/sh
# This script should be run after starting the server
# Any processes that need to be started should be listed here

# Oracle
# /usr/ust/scripts/oracle_start

# Removes the /usr/monitor/MONITOR.STOP file which restarts monitor
/usr/ust/scripts/start_monitor
