---
# Loop through and create administrator accounts
- include_vars: vars/admin_users.yml

- name: Creating admins
  user:
    name: "{{ item.key }}"
    state: "{{ item.value.status }}"
    comment: "{{ item.value.gecos }}"
    uid: "{{ item.value.uid }}"
    group: "user66"
    groups: "{{ item.value.groups }}"
    shell: "{{ item.value.shell }}"
    create_home: "yes"
    home: "/home/{{ item.key }}"
    password: "*K*"
  loop: "{{ lookup('dict', admin_details )}}"
  
- name: Remove password aging
  command: /usr/bin/chage -d -1 -E -1 -m -1 -M -1 -W -1 {{ item.key }}
  loop: "{{ lookup('dict', admin_details )}}"

  # - name: Adding public public_keys
  # authorized_key:
    # user: "{{ item.key }}"
    # state: "{{ item.value.status }}"
    # key: "{{ lookup('file', 'files/public_keys/{{ item.value.key_file }}') }}"
    # loop: "{{ lookup('dict', admin_details, {'skip_missing': True} )}}"
