---
# update alternatives list

- name: alternative link python to python3
  alternatives:
    name: python
    path: /usr/bin/python3
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
