---
- name: Configure krb.conf
  template:
    src: templates/krb_conf.j2
    dest: /etc/krb.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Configure krb5.conf
  template:
    src: templates/krb5_conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Configure sssd.conf
  template:
    src: templates/sssd_conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'
  notify: restart sssd
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"

- name: Place password-auth-ac
  template:
    src: files/password-auth-ac_rhel7
    dest: /etc/pam.d/password-auth
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Place password-auth-ac
  template:
    src: files/password-auth-ac_rhel8
    dest: /etc/pam.d/password-auth
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"

- name: Place system-auth-ac
  template:
    src: files/system-auth-ac_rhel7
    dest: /etc/pam.d/system-auth-ac
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Place system-auth-ac
  template:
    src: files/system-auth-ac_rhel8
    dest: /etc/pam.d/system-auth
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"

- name: Place nsswitch RHEL 7
  template:
    src: files/nsswitch.conf-rhel7
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Place nsswitch RHEL 8
  template:
    src: files/nsswitch.conf-rhel8
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
