---
- name: identifing primary network interface
  debug:
    msg: interface is {{ ansible_facts.ansible_default_ipv4.alias }}

- name: update PEERDNS in the ifcfg
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_facts.ansible_default_ipv4.alias }}
    state: present
    regexp: ^PEERDNS
    line: PEERDNS=no
    create: true

- name: update PEERROUTES in the ifcfg
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_facts.ansible_default_ipv4.alias }}
    state: present
    regexp: ^PEERROUTES
    line: PEERROUTES=no
    create: true

- name: updating NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted

- name: configure resolv.conf
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
