---
- name: Enable RHEL 7 repositories
  rhsm_repository:
    name:
      - rhel-7-server*
      - "*epel-7-server-x86_64"
    state: enabled
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Enable RHEL 8 repositories
  rhsm_repository:
    name:
      - rhel-8-for*
      - "*epel-8-server-x86_64"
    state: enabled
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
