---
- name: Create afterboot
  template:
    src: files/afterboot
    dest: /usr/local/scripts/afterboot
    owner: root
    group: root
    mode: '0744'

- name: Create b4shutdown
  template:
    src: files/b4shutdown
    dest: /usr/local/scripts/b4shutdown
    owner: root
    group: root
    mode: '0744'

- name: Create cop_srvr_base
  template:
    src: files/{{ cop_srvr_base_loc }}
    dest: /etc/cron.d/cop_srvr_base
    owner: root
    group: root
    mode: '0644'

- name: Create cop_srvr_performance
  template:
    src: files/{{ cop_srvr_performance_loc }}
    dest: /etc/cron.d/cop_srvr_performance
    owner: root
    group: root
    mode: '0644'

- name: Create cop_srvr_local
  template:
    src: files/{{ cop_srvr_local_loc }}
    dest: /etc/cron.d/cop_srvr_local
    owner: root
    group: root
    mode: '0644'

- name: copy sudoers defaults
  template:
    src: files/sudoers.d/defaults
    dest: /etc/sudoers.d/defaults
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers nexpose
  template:
    src: files/sudoers.d/nexpose
    dest: /etc/sudoers.d/nexpose
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers omsagent
  template:
    src: files/sudoers.d/omsagent
    dest: /etc/sudoers.d/omsagent
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers unixadmin
  template:
    src: files/sudoers.d/unixadmin
    dest: /etc/sudoers.d/unixadmin
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers unixauto
  template:
    src: files/sudoers.d/unixauto
    dest: /etc/sudoers.d/unixauto
    owner: root
    group: root
    mode: '0440'

- name: create netfiles directory 
  file:
    path: /usr/local/logs/cmpfiles/netfiles
    state: directory
    owner: root 
    group: root
    mode: '0755'
