---
# task to mount

- name: Mount /usr/ust
  mount:
    fstype: nfs
    name: "{{ nfs_common.ust_point }}"
    opts: "{{ nfs_common.mount_opts }}"
    src: "{{ nfs.ust_src }}"
    state: mounted

- name: Mount /globalUnix
  mount:
    fstype: nfs
    name: "{{ nfs_common.gu_point }}"
    opts: "{{ nfs_common.mount_opts }}"
    src: "{{ nfs.gu_src }}"
    state: mounted
...
