---
- name: installing common packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - nmon
    - oddjob
    - oddjob-mkhomedir
    - zsh

- name: Installing kerberos packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - pam_krb5
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Installing SSSD packages
  yum:
    name: "{{ packages }} "
    state: latest
  vars:
    packages:
    - adcli
    - authconfig
    - krb5-workstation
    - realmd
    - sssd
    - sssd-tools
    - sssd-ad
  when:
    - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
