---

- name: Updating SSHD host key permissions
  file:
    path: "/etc/ssh/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  notify: restart sshd
  loop:
    - ssh_host_ecdsa_key
    - ssh_host_ed25519_key
    - ssh_host_rsa_key

- name: Updating SSHD host public key permissions
  file:
    path: "/etc/ssh/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd
  loop:
    - ssh_host_ecdsa_key.pub
    - ssh_host_ed25519_key.pub
    - ssh_host_rsa_key.pub

- name: Updating SSHD_CONFIG
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify: restart sshd
