---
- name: copy sudoers defaults
  template:
    src: files/sudoers.d/defaults
    dest: /etc/sudoers.d/defaults
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers nexpose
  template:
    src: files/sudoers.d/nexpose
    dest: /etc/sudoers.d/nexpose
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers omsagent
  template:
    src: files/sudoers.d/omsagent
    dest: /etc/sudoers.d/omsagent
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers unixadmin
  template:
    src: files/sudoers.d/unixadmin
    dest: /etc/sudoers.d/unixadmin
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers dcaunix
  template:
    src: files/sudoers.d/dcaunix
    dest: /etc/sudoers.d/dcaunix
    owner: root
    group: root
    mode: '0440'

- name: copy sudoers unixauto
  template:
    src: files/sudoers.d/unixauto
    dest: /etc/sudoers.d/unixauto
    owner: root
    group: root
    mode: '0440'
